version: 0.2
env:
  variables:
    TZ_NEW_VERSION: "true"
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Copying settings to configure maven..."
      - wget -c https://bolbuildutils.s3.amazonaws.com/utilsBOLDeploy.sh
      - chmod +x utilsBOLDeploy.sh ; ./utilsBOLDeploy.sh v1 $CODECOMMIT_REPOSITORY_NAME none
      - aws --version
      #- export CODEARTIFACT_AUTH_TOKEN=`aws codeartifact get-authorization-token --domain banesco-backbase --domain-owner $BB_SHARED_ACCT_ID --query authorizationToken --output text`
  pre_build:
    commands:
      - echo "Logging in to Amazon ECR..."
      #- aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 644970069543.dkr.ecr.us-east-1.amazonaws.com
      - echo "Prueba de flujo... ! ! ! !"
      - npm version
      - npm install
      - npm ci
      - npm install @playwright/test@1.48.2
      - npx playwright install-deps
      - npx playwright install  
      - DATE=`date +%d%m%y%H%M%S`
      #- npx playwright install --with-de
      - echo $DATE
      - export PLAYWRIGHT_HTML_OUTPUT_DIR=my-report-$DATE 
      - echo $PLAYWRIGHT_HTML_OUTPUT_DIR
      #- ls -al
      #- cat playwright.config.ts
      - sed -i 's/@@@@@@@@/"$PLAYWRIGHT_HTML_OUTPUT_DIR"/g' playwright.config.ts
      #- cat playwright.config.ts
      - npx playwright test
      - chmod +x .aws/codebuild/indexGenerator.sh
      #- aws s3 cp my-report-$DATE s3://mercury.banesco.do/ --recursive
      - echo $PLAYWRIGHT_HTML_OUTPUT_DIR
      - ls -al $PLAYWRIGHT_HTML_OUTPUT_DIR
      - aws s3 cp $PLAYWRIGHT_HTML_OUTPUT_DIR/ s3://$BUCKET_S3/$PLAYWRIGHT_HTML_OUTPUT_DIR/ --recursive
      - .aws/codebuild/indexGenerator.sh $BUCKET_S3
      - aws s3 cp index.html s3://$BUCKET_S3/index.html
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID_CF --paths "/*"
      #- aws s3 cp my-report/ s3://bol-test-funcional/ --recursive
  build:
    commands:
      - echo "Generating version for build!! ..."
